services:
  friends_of_sulu.sulu_attributes.attribute_field_descriptor_factory:
      class: FriendsOfSulu\Bundle\SuluAttributesBundle\AttributeListProvider\AttributeFieldDescriptorFactory
      decorates: sulu_core.list_builder.field_descriptor_factory
      arguments:
          - '@friends_of_sulu.sulu_attributes.attribute_field_descriptor_factory.inner'

